### ISSUE TITLE
add 1.4.2 linux support

### ISSUE THREAD

**Issue by oryband** [travis-ci/gimme#10]
gotta stay updated :)
https://golang.org/dl/

**Comment by tamird** [comment]
appears to be done

**Comment by tianon** [comment]
Yeah, one of the main points of the way `gimme` works is that new versions will actually start working without any additional effort on our part, just by nature of the tarballs/source being available.  The `.known-....` files are literally just for the `.travis.yml` file within this repo to test `gimme` against known versions. :smile:
