### ISSUE TITLE
"gimme stable" installs go 1.8.3, not 1.9

### ISSUE THREAD

**Issue by albertito** [travis-ci/gimme#111]
When using "gimme stable" (tried via travis-ci.org), I get 1.8.3 instead of 1.9.

I think this is due to [this page](https://www.googleapis.com/storage/v1/b/golang/o?fields=items%2Fname&maxResults=999999) referenced in [gimme:440](https://github.com/travis-ci/gimme/blob/master/gimme#L440), which does not include 1.9.

I don't know why, or who owns it, but thought to file the bug here as I imagine you would know.

Thanks!

**Comment by euank** [comment]
I've posted a patch that I think fixes your issue. See the xref link above.

The reason that google storage listing doesn't have 1.9 is that it only shows the first 1000 results due to pagination. The next page of results does include 1.9.

**Comment by frioux** [comment]
FWIW for me stable is  giving **1.7**: https://travis-ci.org/frioux/leatherman/builds/329185053#L433

I would love for this to be fixed so that I can avoid hardcoding a version number
