### ISSUE TITLE
Versions metadata on golang.org

### ISSUE THREAD

**Issue by AlekSi** [travis-ci/gimme#135]
gimme currently parses https://golang.org/dl/ HTML output. How brittle is it? Will we significantly benefit from having plain text or JSON metadata file hosted on golang.org? If yes, what is our preference for this file format?

**Comment by philpennock** [comment]
Looks for any line matching RE `go([[:alnum:]\.]*)\.src.*` and emits all of those, which gets sorted and uniq'd (precise mechanism for that changes in a current PR).

RE parsing HTML is never going to be awesome, but unless the Go devs fundamentally change now they name releases, or stop publishing source, we should be okay.

**Comment by AlekSi** [comment]
Ok, so this is not a problem.

**Comment by philpennock** [comment]
(To be clear: if machine-format metadata existed, I'd jump at using it; I'm not insane.  Just it's not pressing enough to ask others to do work to benefit us.)
