### ISSUE TITLE
Time for 1.5.0 ?

### ISSUE THREAD

**Issue by philpennock** [travis-ci/gimme#141]
I think reconsidering the bootstrap handling is big enough to not have anything else block on it.

Is it time for a 1.5.0 release?  Mostly, it's all the little glitches around the Go 1.10 release which make me want something out.

* A bunch of fixes relating to `1.10` vs `1.1`, `1.2`
  + This does not relate to how Travis parses YAML, but people writing `1.10.x` should help there
* Handle `.x` suffices natively in `gimme`
* Be able to specify arbitrary git tags or specifiers
* Have a cached list of known versions
* Add `--resolve` to let a caller query what gimme thinks a label becomes (for handling `.x`)
* `GIMME_ENV` now always emitted, including for existing builds
* Portability fixes
* Simplified HTML scraping

**Comment by AlekSi** [comment]
I think `.x` is big enough by itself. +1 from me.

**Comment by markus-wa** [comment]
+1 as `stable` is broken in 1.4 and earlier (https://github.com/travis-ci/gimme/commit/353c05781522e1d42dff6eb611655887aedf15e6)

**Comment by philpennock** [comment]
I approved and merged a prep-for-release PR ( #142 ) the other day.  @meatballhat might chime in with the status here?

**Comment by philpennock** [comment]
ping

**Comment by markus-wa** [comment]
Any news on this?

**Comment by philpennock** [comment]
This was released.
https://github.com/travis-ci/gimme/releases/tag/v1.5.0

No idea if/when Travis will be using this.  But 1.5.0 exists now.
