### ISSUE TITLE
gimme stable installs go 1.9.6

### ISSUE THREAD

**Issue by cloudlena** [travis-ci/gimme#145]
`gimme stable` installs go 1.9.6 but the latest stable version would be 1.10.2. I'm guessing that the parsing is wrong and it thinks that `1.9*` is newer than `1.1*`.

**Comment by philpennock** [comment]
`GIMME_DEBUG=t gimme stable` shows go1.10.2 being installed.

What version do you see from `gimme version`?  If you clone the gimme repo and invoke gimme from there, what happens?  How are you getting gimme?  We've already fixed many issues around 1.10 vs 1.9 and are just waiting on someone from inside travis-ci to officially cut Gimme 1.5.0 and perhaps ensure their images include updated gimme.

**Comment by cloudlena** [comment]
I'm running it on Travis CI for the following project: https://github.com/mastertinner/s3manager There you can see the config in `.travis.yml` and the build logs by following the link behind the build badge. Maybe the `gimme` version of Travis CI is out of date.

**Comment by philpennock** [comment]
Travis-CI is behind.  The fixes you want are in `gimme`, we need someone from travis-ci to update their image, and perhaps to get around to cutting 1.5.0 of gimme first.

**Comment by cloudlena** [comment]
Thanks, @philpennock. I'll close this then.
