### ISSUE TITLE
gimme 1.x is selecting a beta release

### ISSUE THREAD

**Issue by FiloSottile** [travis-ci/gimme#157]
```
$ GIMME_OUTPUT="$(gimme 1.x | tee -a $HOME/.bashrc)" && eval "$GIMME_OUTPUT"
go version go1.11beta3 linux/amd64
```

https://travis-ci.org/FiloSottile/mkcert/builds/415286366

This is not expected behavior according to the README:

> Use of .x will not find release candidates, alphas, betas or other non-release versions

**Comment by AlekSi** [comment]
Hi Filippo,

That was reported in #152, fixed in #153 and included into v1.5.1. Then there is https://github.com/travis-ci/travis-build/pull/1442.

@joepvd Is it due to v1.5.1 is tagged, but there is no corresponding [release](https://github.com/travis-ci/gimme/releases)?

**Comment by dmitshur** [comment]
In addition to what @AlekSi mentioned above, there is also issue https://github.com/travis-ci/travis-ci/issues/9652 tracking this.

It seems the only remaining step to resolve this is for Travis CI builds to start using gimme v1.5.1 instead of v1.5.0.

**Comment by dmitshur** [comment]
@FiloSottile This issue should be resolved as of https://github.com/travis-ci/travis-build/pull/1442#issuecomment-413131247. Try restarting your failed builds. If it's resolved for you too, this issue can be closed.

**Comment by Lyoness** [comment]
Hi @FiloSottile can you confirm this is resolved on your end too by restarting your failed builds?

**Comment by AlekSi** [comment]
Checked again – it works as described at README. Closing.
