### ISSUE TITLE
Installing `tip` is busted omg

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/gimme#16]
See https://github.com/travis-ci/travis-ci/issues/4101

**Comment by tianon** [comment]
So, thinking about why this is, I'm inclined to say that we might have done this on purpose, since `tip` _does_ require 1.4, but we didn't want trying to install tip to just randomly go download 1.4 automatically willy-nilly (especially since that'd grab 1.4.0, not 1.4.latest).

**Comment by tianon** [comment]
For reference, the code in question:
https://github.com/meatballhat/gimme/blob/f2342466bf48a069fd0a9a0112c18dd863de12be/gimme#L162-L180

**Comment by meatballhat** [comment]
That's absolutely right, so this is a bit of a gimme issue and a bit of a
Travis-specific issue, as the 1.4 bootstrap installation is _supposed_ to
be there ... but maybe isn't :scream_cat:

**Comment by tianon** [comment]
Oh right!  We had the Travis scripts explicitly doing `gimme 1.4` before any other `gimme` happens (which is kind of amusing because it'd be 1.4.0, not 1.4.latest since upstream doesn't believe in the `.0` specifier).

**Comment by al3xdm** [comment]
Any way for us to work around this until a fix gets made? Or pointers on what you see a fix looking like so we could help roll one?

**Comment by pierrre** [comment]
Huuu, Go tip works for me: https://travis-ci.org/pierrre/imageserver/jobs/69973837

**Comment by al3xdm** [comment]
We're on the newer container infrastructure running ubuntu 14.04 (dist: trusty) which is why you aren't seeing the issue. 14.04 travis doesn't seem to have a working go installation set, unlike the build infrastructure you're running which picks up the existing go installation before "gimmie tip" runs

**Comment by pierrre** [comment]
https://travis-ci.org/pierrre/archivefile/jobs/55290183
Is this one on the new architecture? (I don't use sudo in this project)

Edit:
Ubuntu 12.04.5 LTS
NO

**Comment by al3xdm** [comment]
Nope, see from build output:

```
Operating System Details
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise
```

On the new infrastructure looks like:

```
Build system information
Build language: go
Build dist: trusty
Build image provisioning date and time
Fri Jun  5 21:52:26 UTC 2015
Operating System Details
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:    14.04
Codename:   trusty
```

**Comment by tianon** [comment]
@meatballhat I still think this is a Travis-specific bug -- WDYT?

I suppose I could be convinced to think otherwise if you think a `--auto-download-bootstrap-if-necessary` flag makes sense, but that feels kind of hanky compared to just making sure a recent compiled version of Go is available before trying to install `tip` (from the `gimme` point of view).

**Comment by kylewolfe** [comment]
Here's another instance where tip is broken: https://travis-ci.org/kylewolfe/rumble/builds/87947440

**Comment by meatballhat** [comment]
@kylewolfe Hey there.  What I'm seeing in your log is:

``` bash
$ eval "$(gimme tip)"
go version devel +a4fb8c1 Sun Nov 1 21:17:01 2015 +0000 linux/amd64
```

This means (to me) that the installation of `tip` succeeded, at least from a `gimme` perspective.  What part of this job do you consider an example of `tip` being broken?

**Comment by kylewolfe** [comment]
Looks like I linked the wrong build, or reran it at some point. Here you go: https://travis-ci.org/kylewolfe/rumble/builds/87912732

```
$ eval "$(gimme tip)"
go version devel +492a62e Wed Oct 28 05:53:28 2015 +0000 linux/amd64
```

That commit hash is from April: https://github.com/golang/go/commit/492a62e

**Comment by meatballhat** [comment]
@kylewolfe thanks for the super fast follow-up.  I'm still having trouble understanding what part of the build is an example of `tip` being broken, as the `eval "$(gimme tip)"` command itself is successful.

**Comment by kylewolfe** [comment]
The command doesn't fail, however it certainly did not retrieve the tip of the repo.

**Comment by meatballhat** [comment]
@kylewolfe OK, I understand now.  Even though the result should be the same, are you able to switch to `master`?  Was this a transient problem, or is it still happening?

**Comment by kylewolfe** [comment]
@meatballhat, because the first link I submitted appears to have brought in the correct tip, I'm assuming the problem is intermittent.

I worked around the issue by supplying a tag of 1.5 in my .travis.yml file rather than -tip.

**Comment by meatballhat** [comment]
@kylewolfe :+1: gotcha.  It's odd since we depend on pulling latest golang sources from github, and `gimme` _should_ fail if the `git pull` fails for any reason.

**Comment by meatballhat** [comment]
I'm closing this out for now, but please yell if you're still seeing intermittent issues!
