### ISSUE TITLE
"oldstable" does not work on Travis

### ISSUE THREAD

**Issue by nkovacs** [travis-ci/gimme#179]
On my computer, using `GIMME_GO_VERSION=oldstable gimme -r` returns 1.11.13 with gimme v1.5.3. On Travis, the job fails with `gimme: version specifier 'oldstable' unknown` even though it's also using gimme v1.5.3: https://travis-ci.org/nkovacs/go-tz/jobs/579740549 ([stable works](https://travis-ci.org/nkovacs/go-tz/jobs/579740548))

**Comment by abhinav** [comment]
The `stable`/`oldstable` feature has been merged but not released yet. It's not clear when a release will be tagged (which is presumably a pre-requisite for it to be available on Travis machines).

Are you sure it's working for you locally with gimme 1.5.3?

```
$ gimme --version
v1.5.3
$ GIMME_GO_VERSION=oldstable gimme -r
oldstable
```

**Comment by nkovacs** [comment]
I installed gimme using the instructions in the readme:

```
curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
chmod +x ~/bin/gimme
```

This version claims to be 1.5.3 and resolves oldstable as 1.12.9 (since 1.13 just got released a few days ago), but I guess it's not actually 1.5.3, but master that hasn't had the version number incremented yet.

**Comment by gravis** [comment]
Any news on this? It would be very handy to stick to a go matrix with `old-stable` and `stable`.

**Comment by kolyshkin** [comment]
Travis says to report bugs to their community forum, so I created this:
https://travis-ci.community/t/cant-specify-oldstable-as-go-version-in-travis-yml/7670

**Comment by AlekSi** [comment]
1.5.4 is released. Does it work now?

**Comment by kolyshkin** [comment]
> Does it work now?

testing on https://github.com/opencontainers/runc/pull/2538 ...

**Comment by kolyshkin** [comment]
> testing on opencontainers/runc#2538 ...

Yes, it works now, so I guess the issue can be closed.
