### ISSUE TITLE
Release 1.5.4

### ISSUE THREAD

**Issue by kolyshkin** [travis-ci/gimme#185]
Can a new (1.5.4) release please be made? This should help address #179 since Travis is using last released version (1.5.3) which does not have the ability to specify the "oldstable" feature.

This should help a lot to many open source project maintainers

@BanzaiMan @tianon PTAL

**Comment by kolyshkin** [comment]
@tianon @BanzaiMan very please

**Comment by AlekSi** [comment]
I think this issue can be closed

**Comment by kolyshkin** [comment]
Yes, thank you, version 1.5.4 was released on April 30th, see https://github.com/travis-ci/gimme/releases/tag/v1.5.4
