### ISSUE TITLE
`gimme list` does not report correct system version

### ISSUE THREAD

**Issue by woosley** [travis-ci/gimme#201]
I think I happened to use gimme because of [kind](https://github.com/kubernetes-sigs/kind/) project, it auto installs go 1.17 to /Users/woosleyxu/.gimme/versions/go1.17.darwin.amd64, however, I don't think the below behavior is correct

```
 woosleyxu@C02CQ7DBMD6M ~ :gimme list
1.17
 woosleyxu@C02CQ7DBMD6M  ~ :go version
go version go1.14.4 darwin/amd64
```
it seems to me gimme should correctly report the system go version here instead of the the version installed by Gimme.

**Comment by tianon** [comment]
This is partially by design -- `gimme` only knows about / manages the things it specifically installed.

**Comment by woosley** [comment]
looking at the features provided, is it safe to conclude that gimme is not a full-fledged go version management tool like pyenv in python? or is it in gimme's roadmap?

**Comment by tianon** [comment]
You are correct, it is not. It was developed specifically for the use of Travis CI, and frankly hasn't really been maintained since the folks who worked there that originally kicked it off left. 😔

**Comment by woosley** [comment]
thanks for the explanation.
