### ISSUE TITLE
Use Go 1.6 as bootstrap

### ISSUE THREAD

**Issue by pierrre** [travis-ci/gimme#27]
Go 1.6beta1 is out, can you add Go 1.6 as a bootstrap candidate?
By the way, shouldn't you test candidates in reverse order? (1.6, 1.5 and 1.4).
It makes more sense to use the most recent version of Go.

Also, the ARM architecture is now officially available in downloads (https://golang.org/dl/#go1.6beta1)
But they only provide the ARM6 binary: https://storage.googleapis.com/golang/go1.6beta1.linux-arm6.tar.gz
In the URL: it's "arm6" and not "arm".
But https://storage.googleapis.com/golang/go1.6beta1.linux-arm.tar.gz also works...

**Comment by tianon** [comment]
I agree on all counts -- trying versions in descending order makes a lot of sense, and our ARM support is definitely lacking (we also need arm64 now too, although the "bootstrap" story there is more challenging)

@meatballhat do we have ARM Travis workers yet? :innocent: (if you could snag some decent `arm64` hardware, you can run `armv5`/`armel`, `armv6`/rpi1, and `armv7`/`armhf`/rpi2 builds on it too :smile:)
