### ISSUE TITLE
Add 1.6 release candidate go1.6rc1

### ISSUE THREAD

**Issue by montanaflynn** [travis-ci/gimme#33]
https://golang.org/dl/#go1.6rc1

**Comment by pierrre** [comment]
By the way, the correct URL for ARM is now https://storage.googleapis.com/golang/go1.6rc1.linux-armv6l.tar.gz

**Comment by tianon** [comment]
#32 added it to our testing lists, and #34 fixes the way we reference ARM binaries :+1:

**Comment by montanaflynn** [comment]
Awesome, thanks!
