### ISSUE TITLE
Alias for `stable`

### ISSUE THREAD

**Issue by thatguystone** [travis-ci/gimme#39]
It would be nice if there were an alias for the latest stable release of go (like there is for `tip`) so that rather than having to manually update each .travis.yml in all of my projects to the newest version of go, I could just use the alias `stable`, and it would pick it up with each new run.

While supporting older versions is obviously nice, the go team only supports the current stable release (https://golang.org/doc/devel/release.html#policy), and I think it would be a good idea to encourage people to use (and test on) what is currently supported.

**Comment by tianon** [comment]
I totally agree, but with the caveat that it's challenging to implement such a thing without hard coding the version number of the latest release, which would prevent this from being up to date within Travis for a while after a new release drops without human time being spent to do so.

**Comment by tianon** [comment]
(So if we can overcome that somehow in a clean way that isn't likely to break, +1)

**Comment by thatguystone** [comment]
Yeah, that is the troublesome part. I have 2 ideas on the matter:
1. Do you know any existing list of golang stable releases (that is, not including rcs, betas, etc), that is easy to parse from bash? I've looked around, and I haven't seen any. (Andrew Gerrand said he would look into it, but nothing seems to have come from it: https://groups.google.com/d/msg/golang-nuts/WDX2hJfqfck/gRNzlCJNvxkJ)
2. We could create a `.current-stable` (along side `.known-*` in the repo) that gimme could query periodically to check for updates, at least until there's another source.

**Comment by ahmetb** [comment]
:+1: +1 on this.

**Comment by asottile** [comment]
fwiw this has directory listing in xml: https://storage.googleapis.com/golang/ (I originally asked for this in golang/go#13220)

It shouldn't be too difficult to parse it and do a natural sort on the version numbers

Here's a hackety stab at it:

``` bash
$ curl https://storage.googleapis.com/golang/ > listing
$ grep -Eo '<Key>[^<]*</Key>' listing | cut -d'>' -f2 | cut -d'<' -f1 | grep '.src.tar.gz$' | grep -Ev '(rc|beta)[0-9]'
go1.2.2.src.tar.gz
go1.3.1.src.tar.gz
go1.3.2.src.tar.gz
go1.3.3.src.tar.gz
go1.3.src.tar.gz
go1.4.1.src.tar.gz
go1.4.2.src.tar.gz
go1.4.3.src.tar.gz
go1.4.src.tar.gz
go1.5.1.src.tar.gz
go1.5.2.src.tar.gz
go1.5.3.src.tar.gz
go1.5.src.tar.gz
go1.6.src.tar.gz
```

**Comment by mvdan** [comment]
FWIW, the version before the current stable (1.5 now that 1.6 is out) isn't completely unsupported:

> As a special case, we issue minor revisions for critical security problems in both the current release and the previous release. For example, if Go 1.5 is the current release then we will issue minor revisions to fix critical security problems in both Go 1.4 and Go 1.5 as they arise. See the security policy for more details.

https://golang.org/doc/devel/release.html

**Comment by thatguystone** [comment]
@asottile My only concern with that list is sorting (1.5.2 < 1.5). GNU Coreutils' sort has -V (version sort), but I don't see this flag on BSD, I like Brad Fitz's suggestion of implementing `https://golang.org/dl/?format=json`. I'll look into that.

**Comment by tianon** [comment]
Yeah, and parsing XML via shell is hairy and error-prone. :cry:

**Comment by asottile** [comment]
json is going to have similar problems (wrt parsing).  Why not use `python` or some other higher-level scripting language to do the parsing / sorting?

**Comment by thatguystone** [comment]
So, with python, the current stable can be fetched with:

``` python
from __future__ import print_function

import codecs, itertools, json, re
from distutils.version import StrictVersion

try:
    from urllib.request import urlopen
except ImportError:
    from urllib2 import urlopen

resp = urlopen('https://www.googleapis.com/storage/v1/b/golang/o?fields=items%2Fname')
rels = json.load(codecs.getreader('utf-8')(resp))

vre = re.compile('go([\d\.]*).src.*')
vers = list(itertools.chain(*(vre.findall(rel['name']) for rel in rels['items'])))

print(sorted(set(vers), key=StrictVersion)[-1], end='')
```

The problem with this is that it fetches _all_ files from the golang bucket. This isn't the friendliest approach, and as the releases continue to grow, it will only get worse.

**Comment by thatguystone** [comment]
I looked into the idea of adding `https://golang.org/dl/?format=json`, but it just looks like that endpoint would provide basically the same info as the directory listing with niceties like package type, os, and version (all of which can be extracted from the file name). So it seems that the directory listing is the simplest approach.

I've create a pull request for review: #40

**Comment by eduncan911** [comment]
This is sorted correctly (1.5.3 > 1.5):

```
$ curl -silent https://storage.googleapis.com/golang/ | grep -Eo '<Key>[^<]*</Key>' | cut -d'>' -f2 | cut -d'<' -f1 | grep '.src.tar.gz$' | grep -Ev '(rc|beta)[0-9]' | sed 's/\.src\.tar\.gz//' | sort -n -r
go1.6
go1.5.3
go1.5.2
go1.5.1
go1.5
go1.4.3
go1.4.2
go1.4.1
go1.4
go1.3.3
go1.3.2
go1.3.1
go1.3
go1.2.2
```

Using this pattern, you can follow the Go binary naming convention and pull down the filename with:

```
$VAL.[src.]tar.gz
```

Tested in OS X bash, ArchLinux bash and Ubuntu bash.

Or, if all we want is the "Latest Stable Build", use this:

```
$ curl -silent https://storage.googleapis.com/golang/ | grep -Eo '<Key>[^<]*</Key>' | cut -d'>' -f2 | cut -d'<' -f1 | grep '.src.tar.gz$' | grep -Ev '(rc|beta)[0-9]' | sed 's/\.src\.tar\.gz//' | sort -n -r | head -n 1
go1.6
```

^- only returns the latest entry

**Comment by eduncan911** [comment]
just fyi, now that 1.6.1 is out, the above command works perfectly to show 1.6.1 instead of 1.6.  👍 

```
$ curl -silent https://storage.googleapis.com/golang/ | grep -Eo '<Key>[^<]*</Key>' | cut -d'>' -f2 | cut -d'<' -f1 | grep '.src.tar.gz$' | grep -Ev '(rc|beta)[0-9]' | sed 's/\.src\.tar\.gz//' | sort -n -r | head -n 1
go1.6.1
```

**Comment by thatguystone** [comment]
@eduncan911 That's very interesting; thanks for pointing it out. I've updated the pull request to use pure bash instead of python.

**Comment by kodawah** [comment]
I'd love to get this too!

**Comment by kodawah** [comment]
@meatballhat any update on this? It'd be really nice to get this in.

**Comment by meatballhat** [comment]
👋 Specifically for use on Travis, one may now specify a version with `x` in the minor or patch level positions, e.g.:

``` yaml
language: go
go:
- 1.x
- 1.7.x
- 1.6
```

The mapping for this is maintained in [travis-build](https://github.com/travis-ci/travis-build/blob/524f3d812400cbe3aad2a6f332fe748c41bcce65/lib/travis/build/script/go.rb#L18-L33) rather than gimme, as I would like gimme to stay as naïve as possible about versions.

**Comment by kodawah** [comment]
Hi @meatballhat,
thanks for the suggestion but unfortunately this does not seem like a viable solution for this use case.

First of all, this ties gimme to travis, while it's nice to run it standalone on a variety of systems. Secondly, this requires travis-build to keep track of every single go release. Besides being a maintenance burden for you guys, it also requires enterprise installations to keep updating every time a new go release happens.

Overall I still think that a `stable` alias that queries a server and simply parses the string is a pretty good compromise, and since go is committed to semver having a simple string parsing function would keep gimme very naïve about versions.

**Comment by tianon** [comment]
This API endpoint is now running into paging issues, BTW (https://github.com/travis-ci/gimme/issues/93#issuecomment-308575631) :disappointed:

**Comment by eduncan911** [comment]
that's a bummer.  i've been using my solution above in my own upgrade script:

https://github.com/eduncan911/dotfiles/blob/master/bin/upgrade-go.sh#L12

guess i could hardcode it to look for page 2.  👎

**Comment by tianon** [comment]
https://github.com/docker-library/golang/commit/cdeca62eb84c34680e2f4ec018d1d6cfaa818681#diff-25e6ad8ebc5d26ba06d2bcb0b220149c is what I ended up with, but it adds `jq` as a dependency, which isn't great for `gimme`

**Comment by eduncan911** [comment]
well, since this issue was "closed" as a **Will Not Do**, perhaps it's time to just scrape the release page html.  

https://golang.org/dl/

**Comment by philpennock** [comment]
If you're prepared to use `gimme` from the source repo, and accept that `stable` might be slightly behind, depending upon when folks get around to updating the testdata, then:

```sh
sed -n $'/^[1-9][0-9.]*$/{p\nq\n}' < .testdata/binary-linux
```

It currently says `1.8.1` but I'm about to submit a PR which will update it to 1.8.3.
