### ISSUE TITLE
gimme does not try to use existing installations when `GIMME_TYPE`=source

### ISSUE THREAD

**Issue by tcahill** [travis-ci/gimme#43]
Currently, when `GIMME_TYPE` is set to "source", `gimme` does not look for a pre-existing installation of the requested version. This leads to the potential for the current target installation to be selected as the value for `GOROOT_BOOTSTRAP`. This is not allowed, as shown below:

```
##### Building Go bootstrap tool.
cmd/dist
ERROR: $GOROOT_BOOTSTRAP must not be set to $GOROOT
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
```

It seems the solution here is simply to short-circuit when an existing installation is detected as is done for binary installations.

**Comment by tianon** [comment]
I'm guessing that closing this via apcera/gimme#1 wasn't intentional? :wink:

**Comment by tcahill** [comment]
Woops, my mistake!
