### ISSUE TITLE
allow specifying git shas

### ISSUE THREAD

**Issue by danp** [travis-ci/gimme#49]
Tracking go tip/master is good but sometimes it would be nice to grab a specific sha.

[This](https://github.com/travis-ci/gimme/blob/25d0c5945c26d0d2a98375e76df97702afd5a123/gimme#L153) is close but perhaps there could be an attempt at `git reset -q --hard "${1}"`.

**Comment by philpennock** [comment]
Assuming it's not reverted, this should be in the next release.
