### ISSUE TITLE
Does not fail on non-existent versions

### ISSUE THREAD

**Issue by HelloGrayson** [travis-ci/gimme#53]
I [added Go 1.7 to my .travis.yml](https://travis-ci.org/yarpc/yarpc-go/jobs/142840909) file on several projects, assuming things were working.

Looks like I was wrong, the actual version of Go being used is 1.5.1:

```
19.09s$ eval "$(gimme 1.7)"
I don't have any idea what to do with '1.7'.
  (using type 'auto')
$ export GOPATH=$HOME/gopath
$ export PATH=$HOME/gopath/bin:$PATH
$ mkdir -p $HOME/gopath/src/github.com/yarpc/yarpc-go
$ rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/yarpc/yarpc-go/
$ export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/yarpc/yarpc-go
$ cd $HOME/gopath/src/github.com/yarpc/yarpc-go
$ gimme version
v0.2.3
$ go version
go version go1.5.1 linux/amd64
```

Instead of silently failing and using the default version of Go, I would expect Gimme to exit with a non-0 status code, so that the build fails.

Discovered in https://github.com/crossdock/crossdock-go/pull/6

**Comment by HelloGrayson** [comment]
Actually, this looks like a problem with Travis itself - it's running gimme in an eval:

```
$ eval "$(gimme 1.7)"
I don't have any idea what to do with '1.7'.
  (using type 'auto')

$ echo $?
0
```

If you run gimme directly, it exits with a `1` status code:

```
$ gimme 1.7
I don't have any idea what to do with '1.7'.
  (using type 'auto')

$ echo $?
1
```

Perhaps this issue should be moved...?

**Comment by tianon** [comment]
Sounds like Travis might need `set -o pipefail` or to do the `gimme` in a separate line from `eval`, ie:

``` bash
gimme="$(gimme 1.7)"
eval "$gimme"
```

**Comment by HelloGrayson** [comment]
@tianon how do I get this into the right peoples hands?

**Comment by HelloGrayson** [comment]
Trying to reach out to @travisci on 'ze twitter - https://twitter.com/breerly/status/752967441043496960

**Comment by meatballhat** [comment]
@breerly yo, lookin now! 😸

**Comment by meatballhat** [comment]
@breerly Are you unblocked for now?  I know `1.7rc1` to work.

**Comment by HelloGrayson** [comment]
@meatballhat I'm not necessarily blocked - I've removed `1.7` from projects `.travis.yml` list of Go versions to test.

The problem is that having `1.7` results in `1.5.1` being ran, instead of failing with "1.7 is not an available Go version". This has lead me to believe several projects are being verified against 1.7, when they aren't.

(p.s. I don't work for Travis)

**Comment by meatballhat** [comment]
@breerly Gotcha.  I'm working with @BanzaiMan to get a fix applied to travis-ci/travis-build.  I'll leave this issue open until it's corrected upstream.

**Comment by HelloGrayson** [comment]
@meatballhat you rock! :hurtrealbad:

**Comment by BanzaiMan** [comment]
Thanks for reporting. I'm going to close this one here in favor of https://github.com/travis-ci/travis-ci/issues/6299, since this is not a gimme issue.
