### ISSUE TITLE
Why is GIMME_ENV exported for new installs (only)?

### ISSUE THREAD

**Issue by philpennock** [travis-ci/gimme#67]
@meatballhat and others ...

At present, `export GIMME_ENV=...` is emitted to stdout whenever a new version is built/installed, but not when an existing installation is found and used.
1. Is there a rationale to the inconsistency?  Or just a bug?
2. What is the intended purpose of this environment variable?
3. Does anything actually use it, or should we remove it?

**Comment by meatballhat** [comment]
> 1. Is there a rationale to the inconsistency? Or just a bug?

I can't think of a reason why it should be inconsistent.  I'd like it to be consistent.  I guess that makes it a bug!

> 2. What is the intended purpose of this environment variable?

Informational, mostly (I think).

> 3. Does anything actually use it, or should we remove it?

I dunno!  And also I dunno!
