### ISSUE TITLE
Golang 1.1 not supported anymore?

### ISSUE THREAD

**Issue by yookoala** [travis-ci/gimme#70]
Hello. I'm using Travis CI for testing on macos. They uses gimme to fetch different Golang versions.

My latest build runs into error and here is the message:

```
Installing gimme from https://raw.githubusercontent.com/travis-ci/gimme/v1.0.0/gimme

115.84s$ GIMME_OUTPUT=$(gimme 1.1) && eval "$GIMME_OUTPUT"

I don't have any idea what to do with '1.1'.

  (using type 'auto')

The command "GIMME_OUTPUT=$(gimme 1.1) && eval "$GIMME_OUTPUT"" failed and exited with 1 during .
```

So apparently `gimme 1.1` some how fails and the build fails.

I couldn't find the "supported go version" in gimme's site. Does gimme currently support Go 1.1?

**Comment by yookoala** [comment]
The job I referred to:
[https://travis-ci.org/go-restit/lzjson/jobs/165196197](https://travis-ci.org/go-restit/lzjson/jobs/165196197)

**Comment by philpennock** [comment]
What happens if you change the install URL from referencing `v1.0.0` to`master` ?

**Comment by yookoala** [comment]
I'm not sure how I can do it on Travis. Any documentation on this?

**Comment by yookoala** [comment]
Just checked the build history, the older version of gimme seems to work with command `gimme 1.1`:

```
Installing gimme from https://raw.githubusercontent.com/travis-ci/gimme/v0.2.4/gimme

6.00s$ eval "$(gimme 1.1)"

go version go1.1 darwin/amd64
```

Reference:
https://travis-ci.org/go-restit/lzjson/jobs/125344839

**Comment by philpennock** [comment]
Looks like nothing older than 1.2.2 is still available from the official Golang website:  https://golang.org/dl/

@meatballhat Has gimme yet had to figure out an "official" stance on this?  It seems to me that "gimme only supports downloading versions which the Go devs make available, when they withdraw a version, gimme will stop supporting it." is pretty sane.

Looks like commit 2006b16 removed these old versions, simply because they're unavailable for download.

**Comment by philpennock** [comment]
(which means that any instances of `$(gimme 1.1)` working just means that its an older OS image which still has a cached install of 1.1 lingering on-disk and a fresh install would fail)

**Comment by meatballhat** [comment]
>  gimme only supports downloading versions which the Go devs make available, when they withdraw a version, gimme will stop supporting it.

This is where I'm arriving, too.  I support having this (or something like it) in the README.

You're exactly right about some older stack images having now-unavailable versions like 1.1.  It's a confusing situation, and I can maybe see Travis in particular taking advantage of the mirror URL support that was recently added, but I don't think the gimme tool itself can do anything special to prolong the availability of a given version.
