### ISSUE TITLE
Install current release of Go

### ISSUE THREAD

**Issue by thomasheller** [travis-ci/gimme#88]
It seems that gimme understands:
- installing a specific version of Go (e.g. `1.4.1`)
- installing the development version of Go (i.e. `master`, which gimme calls `tip`)

I'd like to install the current major release of Go (currently 1.8) through gimme.

How could gimme support that?
Is there an easy way for gimme to figure out what the current release is?

**Comment by philpennock** [comment]
`gimme stable`

**Comment by thomasheller** [comment]
Thanks for the pointer!
