### ISSUE TITLE
go 1.4.2 outputs error and populates lots of files in ~/.gimme

### ISSUE THREAD

**Issue by oryband** [travis-ci/gimme#9]
Looks like `1.4.2` still isn't supported in gimme. But when executing `gimme 1.4.2` I get weird errors and `~/.gimme/` gets polluted with lots of files:

``` bash
~ gimme 1.4.2

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
# doesn't return, just hangs
^C
~ tree -L 3 ~/.gimme
/home/ory/.gimme
├── envs
└── versions
    ├── go1.4.2.linux.amd64
    │   ├── api
    │   ├── AUTHORS
    │   ├── bin
    │   ├── blog
    │   ├── CONTRIBUTORS
    │   ├── doc
    │   ├── favicon.ico
    │   ├── include
    │   ├── lib
    │   ├── LICENSE
    │   ├── misc
    │   ├── PATENTS
    │   ├── pkg
    │   ├── README
    │   └── VERSION
    └── go1.4.2.src
        ├── api
        ├── AUTHORS
        ├── bin
        ├── CONTRIBUTORS
        ├── doc
        ├── favicon.ico
        ├── include
        ├── lib
        ├── LICENSE
        ├── make.linux.amd64.log
        ├── misc
        ├── PATENTS
        ├── pkg
        ├── README
        ├── robots.txt
        ├── src
        ├── test
        └── VERSION
```

In addition, I got confused when first trying gimme, and executed `gimme go1.4.2` and `gimme go1.4.1` and this also created garbage `gogo1.4.2` and `gogo1.4.1` dirs.

**Comment by tianon** [comment]
Interesting -- it appears that it tried to download release binaries for your platform (which is the correct behavior), but then they didn't actually work (which is bizarre), so it started compiling from source.

Can you provide the output of `uname -a` for your system, and perhaps some details about the OS?

**Comment by meatballhat** [comment]
I'm unable to reproduce this 😕.  @oryband Please yell if you think this is still a problem!

**Comment by andreasnuesslein** [comment]
If anybody stumbles upon this:

I had the same problem. The issue arose due to corrupt downloads in `/tmp/gimme` .. I'm not sure what caused them in the first place but simply removing (the contents of) `/tmp/gimme/` did the trick.
After that you should be able to `gimme` stuff.
